version: "3.4"
services:
  test_mysql:
    image: mysql:8.0.23
    container_name: test_mysql
    stdin_open: true
    ports:
      - 3305:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - test-mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
  test_mongo:
    image: mongo:4.4
    container_name: test_mongo
    stdin_open: true
    ports:
      - 27016:27017
    volumes:
      - test-mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
  test_redis:
    image: redis:6
    container_name: test_redis
    stdin_open: true
    ports:
      - 6378:6379
    volumes:
      - test-redisdata:/var/lib/redis
volumes:
  test-redisdata:
  test-mysqldata:
  test-mongodata:
networks:
  default:
    external:
      name: test-network
